export const PORT_VAR={
    PORT:"PORT",
};
export const BD_VARS={
    MONGODB_USER:'MONGODB_USER',
    MONGODB_PASSWORD:'MONGODB_PASSWORD',
    MONGODB_URL:'MONGODB_URL',
    MONGODB_DB:'MONGODB_DB',
};
